"""Create Table Attendance

Revision ID: 3aa1bc9df222
Revises: 93a3029f1b02
Create Date: 2024-05-31 01:58:54.912016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa1bc9df222'
down_revision = '93a3029f1b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('shift_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=True),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('scheduled_time_in', sa.DateTime(), nullable=True),
    sa.Column('selfie_photo', sa.String(length=250), nullable=False),
    sa.Column('location_gps', sa.String(length=250), nullable=False),
    sa.Column('event_note', sa.Text(), nullable=False),
    sa.Column('assistance_request', sa.Boolean(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
