"""Create Table Department

Revision ID: 714b30bdf7cd
Revises: e7cd3a55eb52
Create Date: 2024-05-31 01:27:01.549227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714b30bdf7cd'
down_revision = 'e7cd3a55eb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('office_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
