"""Create Table Employee_Personal_Information

Revision ID: b9b24e4bfa8b
Revises: 3aa1bc9df222
Create Date: 2024-05-31 23:33:42.920044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b24e4bfa8b'
down_revision = '3aa1bc9df222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee__personal__information',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('mobile_phone', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('place_of_birth', sa.String(length=100), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=False),
    sa.Column('marital_status', sa.SmallInteger(), nullable=False),
    sa.Column('blood_type', sa.SmallInteger(), nullable=False),
    sa.Column('religion', sa.SmallInteger(), nullable=False),
    sa.Column('identity_type', sa.SmallInteger(), nullable=False),
    sa.Column('identity_number', sa.Integer(), nullable=False),
    sa.Column('identity_expiry_date', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee__personal__information')
    # ### end Alembic commands ###
