"""Create Table Employee_Families

Revision ID: e76293ed926b
Revises: dabf273b1bef
Create Date: 2024-05-31 23:43:29.838896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76293ed926b'
down_revision = 'dabf273b1bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee__families',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=True),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('id_number', sa.Integer(), nullable=False),
    sa.Column('gender', sa.SmallInteger(), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('religion', sa.SmallInteger(), nullable=False),
    sa.Column('marital_status', sa.SmallInteger(), nullable=False),
    sa.Column('job', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee__families')
    # ### end Alembic commands ###
